ALTER TABLE "Plan"
ADD COLUMN "displayName" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Plan"
ADD COLUMN "internalSquadId" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Plan"
ALTER COLUMN "trafficGb" TYPE DOUBLE PRECISION
USING "trafficGb"::DOUBLE PRECISION;

ALTER TABLE "Plan"
ALTER COLUMN "durationDays" TYPE DOUBLE PRECISION
USING "durationDays"::DOUBLE PRECISION;

ALTER TABLE "Setting"
ALTER COLUMN "testDurationDays" TYPE DOUBLE PRECISION
USING "testDurationDays"::DOUBLE PRECISION;

ALTER TABLE "Setting"
ADD COLUMN "testInternalSquadId" TEXT;

ALTER TABLE "Setting"
ADD COLUMN "enableManualPayment" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Setting"
ADD COLUMN "enableTetra98" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Setting"
ADD COLUMN "enablePromos" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Setting"
ADD COLUMN "enableReferrals" BOOLEAN NOT NULL DEFAULT false;
